parameters:
  projectRoot: $(Get-Location)
  outputDirectory: $(Build.ArtifactStagingDirectory)\build\upm\output
  version: $(MRTKVersion)
  buildNumber: $(Build.BuildNumber)

  steps:
  - task: PowerShell@2
    displayName: 'Build UPM packages'
    inputs:
      targetType: filePath
      filePath: ./scripts/packaging/createupmpackages.ps1
      arguments: >
        -ProjectRoot ${{ parameters.projectRoot }}
        -OutputDirectory ${{ parameters.outputDirectory }}
        -Version ${{ parameters.version }}
        -BuildNumber ${{ parameters.buildNumber }}
  