# [Template] Builds and publishes UPM .tgz packages
parameters:
  excludeBuildNumber: 0

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.0'
- ${{ if eq(parameters.excludeBuildNumber, 0) }}:
  - template: buildupm-nobuildnumber.yml
- ${{ if eq(parameters.excludeBuildNumber, 1) }}:
  - template: buildupm/yml
- task: PublishBuildArtifacts@1
  displayName: 'Publish UPM packages'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\build\upm\output'
    ArtifactName: 'mrtk-upm'

