# Pipeline for creating files and running tests for Build Call.

variables:
  System.Debug: true
- template: config/settings.yml
- name: packagingEnabled
  value: false

parameters:
- name: build
  displayName: Build binary selection
  default: common
  values:
  - all
  - common
- name: 

jobs:
- job: BuildCallUnity2019Setup
  displayName: Build Call Unity 2019 binaries and manual testing setup
  timeoutInMinutes: 120
  pool:
    name: On-Prem Unity
    demands:
    - Unity2019.4.8f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - ${{ if contains(parameters.build, 'all') }}:
    - template: templates/buildcallsetup.yml
      parameters:
        packagingEnabled: false
        UnityVersion: $(Unity2019Version)
        MRTKVersion: $(MRTKVersion)
        Binaries: 'all'
  - ${{ if contains(parameters.build, 'common') }}:
    - template: templates/buildcallsetup.yml
      parameters:
        packagingEnabled: false
        UnityVersion: $(Unity2019Version)
        MRTKVersion: $(MRTKVersion)
        Binaries: 'common'

- job: BuildCallUnity2018Setup
  displayName: Build Call Unity 2018 Binaries and manual testing setup
  timeoutInMinutes: 120
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.4.26f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE

  steps:
  - ${{ if contains(parameters.build, 'all') }}:
    - template: templates/buildcallsetup.yml
      parameters:
        packagingEnabled: false
        UnityVersion: $(Unity2018Version)
        MRTKVersion: $(MRTKVersion)
        Binaries: 'all'
  - ${{ if contains(parameters.build, 'common') }}:
    - template: templates/buildcallsetup.yml
      parameters:
        packagingEnabled: false
        UnityVersion: $(Unity2018Version)
        MRTKVersion: $(MRTKVersion)
        Binaries: 'common'
