# Create UPM packages for public OFFICIAL release

variables:
- template: config/settings.yml

parameters:
- name: PreviewNumber
  type: number
  default: -1

jobs:
- job: UPMPublicRelease
  timeoutInMinutes: 30
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/tasks/pack-upm.yml
    parameters:
      ${{ if ge(parameters.PreviewNumber, 0) }}:
        previewNumber: ${{ parameters.PreviewNumber }}
      ${{ if lt(parameters.PreviewNumber, 0) }}:
        previewNumber: ""
