# Create UPM packages for public OFFICIAL release

variables:
- template: config/settings.yml

parameters:
- name: IsFinal
  type: boolean
  default: false
- name: PreviewNumber
  type: string
  default: 0

jobs:
- job: UPMPublicRelease
  timeoutInMinutes: 30
  pool:
    vmImage: windows-2019
  steps:
  - template: templates/tasks/pack-upm.yml
    parameters:
    - ${{ if eq(parameters.IsFinal, false) }}:
        previewNumber: ${{ parameters.PreviewNumber }}
    - ${{ if eq(parameters.IsFinal, true) }}:
        previewNumber: ""
