# Package and publicly release MRTK via UPM

variables:
- template: config/settings.yml

jobs:
- job: PublicUPMPackageRelease
  timeoutInMinutes: 30
  pool:
    name: On-Prem Unity
  steps:
    - template: tasks/upmpackages.yml
      parameters:
        excludeBuildNumber: 1
    - task: PowerShell@2
      displayName: 'UPM packages to registry'
      inputs:
        targetType: filePath
        filePath: ./scripts/packaging/publishupmpackages.ps1
        arguments: >
          -PackageDirectory $(Build.ArtifactStagingDirectory)\build\upm\output
          -RegistryPath $(UpmRegistry)