# This is a scheduled workflow that will run daily to keep mrtk_development with the
# latest in the stabilization branch. This will create a PR every day if there commits
# that haven't been made to mrtk_development.

name: Stabilization to mrtk_development sync

# This schedules a run to occur at 4AM UTC every day
on:  
  schedule:
    - cron: "0 4 * * *"

jobs:
  synchronization_job:
    runs-on: ubuntu-latest
    
    # Since this is a scheduled cron job and is a checked in workflow, this has
    # the capability of running in any forks of this project. This line ensures that
    # this workflow only runs on the main repo, not forks.
    if: ${{ github.repository == "microsoft/MixedRealityToolkit-Unity" }}

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.3
        with:
          source_branch: "prerelease/2.5.0_stabilization"
          destination_branch: "mrtk_development"
          pr_title: "Automated: stabilization to mrtk_development synchronization"
          pr_body: "This an automated pull request to merge latest changes in stabilization back into mrtk_development"
          # This workflow will not create a PR if the change set is empty (i.e. if mrtk_development already contains
          # everything in stabilization, there's no need to create a PR)
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
